// Colony GameTests (Job 4). Imported by src/main.ts for side effects; registration is allowed in
// early-execution (register/registerAsync and the builder methods are early-execution-allowed).
// Run on a dev world with cheats on:  /gametest runset colony   or   /gametest run colony:goto_flat
//
// These drive the REAL runtime through the spec interface only:
//   runtime.adoptBot(simPlayer, name), runtime.submitText(sender, "!goto x y z") with ABSOLUTE coords
//   computed via test.worldLocation(...), and assert on runtime.snapshot().
//
// Structures: GameTest always loads a structure (structureLocation() only moves it), so the tests use
// packs/BP/structures/colony/{flat,walled}.mcstructure generated by scripts/make-structure.mjs.
//
// COORDINATE QUESTION: the runtime calls navigateToLocation with absolute world coords. For a simulated
// player spawned by test.spawnSimulatedPlayer, the engine may interpret those coords relative to the test
// (SimulatedPlayer.move() is documented as "relative to the GameTest"; navigate* is not documented
// either way). Each test is registered twice:
//   colony:<name>      bot from test.spawnSimulatedPlayer (spec's primary path)
//   colony:<name>_abs  bot from top-level spawnSimulatedPlayer (how the runtime spawns bots in play)
// If <name>_abs passes and <name> fails with the bot heading far away, test-spawned bots use
// test-relative navigation coords; the failure message prints the bot's position in both frames.
import { system } from "@minecraft/server";
import { registerAsync } from "@minecraft/server-gametest";
import type { SimulatedPlayer, Test } from "@minecraft/server-gametest";
import type { Vector3 } from "@minecraft/server";
import type { BotId } from "../core/types.js";
import {
  absCell,
  beginTest,
  botName,
  floorY,
  fmt,
  gotoText,
  isIdle,
  near,
  runtime,
  sameVec,
  sender,
  snapStr,
  spawnBot,
  taskStr,
  view,
  waitFor,
  waitGrounded,
  where,
} from "./helpers.js";
import type { SpawnMode } from "./helpers.js";

const CLASS = "colony";
const TAG = "colony";
/** Must match WALLED_TARGET in scripts/make-structure.mjs. */
const WALLED_TARGET = { x: 12, z: 12 };

function coordHint(test: Test, bot: SimulatedPlayer, target: Vector3): string {
  let asRel = "?";
  try {
    asRel = fmt(test.worldLocation(target));
  } catch {
    /* ignore */
  }
  return `bot ${where(test, bot)}; target abs ${fmt(target)}; if abs coords were read as test-relative the bot would head to ${asRel}`;
}

/** The colony must show `id` busy with a goto to `target` issued by `issuer`. Fails the test otherwise. */
function expectTask(test: Test, id: BotId, target: Vector3, issuer: string, what: string): string | undefined {
  const v = view(id);
  const t = v?.task;
  if (!t || t.kind !== "goto" || !sameVec(t.target, target) || t.issuer.name !== issuer) {
    test.fail(`${what}: expected ${v?.name ?? id} busy going to ${fmt(target)} for ${issuer}, got ${taskStr(t)}. ${snapStr()}`);
    return undefined;
  }
  return t.id;
}

// ---------------------------------------------------------------- goto on flat ground

async function gotoFlat(test: Test, mode: SpawnMode): Promise<void> {
  if (!(await beginTest(test))) return;
  const fy = floorY(test);
  if (fy === undefined) return;
  const y = fy + 1;
  const bot = spawnBot(test, mode, { x: 2, y, z: 2 }, botName("GTa"));
  if (!(await waitGrounded(test, [bot]))) return;
  const rt = runtime();
  const id = rt.adoptBot(bot, bot.name);
  if (!isIdle(id)) return test.fail(`adopted bot is not idle: ${snapStr()}`);

  const target = absCell(test, { x: 12, y, z: 12 });
  const a = sender("A", target);
  rt.submitText(a, gotoText(target));
  if (!expectTask(test, id, target, a.name, "after !goto")) return;

  // The pump runs every 4 ticks: the colony goes idle once the executor reports.
  const t = await waitFor(test, () => isIdle(id), 600);
  if (t < 0) return test.fail(`task still active after 600 ticks. ${coordHint(test, bot, target)}. ${snapStr()}`);
  if (!near(bot, target)) {
    return test.fail(`task ended (failed) without arriving. ${coordHint(test, bot, target)}`);
  }
  test.print(`goto_flat(${mode}): arrived and reported done after ${t} ticks.`);
  test.succeed();
}

// ---------------------------------------------------------------- goto unreachable

async function gotoUnreachable(test: Test, mode: SpawnMode): Promise<void> {
  if (!(await beginTest(test))) return;
  const fy = floorY(test);
  if (fy === undefined) return;
  const y = fy + 1;
  const bot = spawnBot(test, mode, { x: 2, y, z: 2 }, botName("GTu"));
  if (!(await waitGrounded(test, [bot]))) return;
  const rt = runtime();
  const id = rt.adoptBot(bot, bot.name);

  // Sealed glass cell around the target (see make-structure.mjs).
  const target = absCell(test, { x: WALLED_TARGET.x, y, z: WALLED_TARGET.z });
  const l = bot.location;
  const startDist = Math.hypot(l.x - target.x, l.y - target.y, l.z - target.z);
  const deadline = 200 + 20 * startDist; // spec timeout: ~200 + 20 x distance ticks
  const a = sender("A", target);
  const t0 = system.currentTick;
  rt.submitText(a, gotoText(target));
  if (!expectTask(test, id, target, a.name, "after !goto")) return;

  // Must NOT get inside, and must give up (become idle) before the timeout -> reason "unreachable".
  let reached = false;
  const freed = await waitFor(
    test,
    () => {
      if (near(bot, target)) reached = true;
      return reached || isIdle(id);
    },
    Math.ceil(deadline + 200),
  );
  if (reached) return test.fail(`bot reached a sealed target - structure or nav is wrong. bot ${where(test, bot)}`);
  if (freed < 0) return test.fail(`bot never gave up on the sealed target (> ${Math.round(deadline + 200)} ticks). ${snapStr()}`);
  const freedAt = system.currentTick - t0;
  if (freedAt >= deadline) {
    return test.fail(`bot gave up only after the timeout (${freedAt} >= ${Math.round(deadline)} ticks): reason was 'timeout', expected 'unreachable'`);
  }
  test.print(
    `goto_unreachable(${mode}): task failed after ${freedAt} ticks (deadline ${Math.round(deadline)}), so reason=unreachable. ` +
      "Only meaningful if goto_flat passes for the same mode (else coords may simply be wrong).",
  );
  test.succeed();
}

// ---------------------------------------------------------------- override flow (two bots)

async function overrideFlow(test: Test, mode: SpawnMode): Promise<void> {
  if (!(await beginTest(test))) return;
  const fy = floorY(test);
  if (fy === undefined) return;
  const y = fy + 1;
  const x = spawnBot(test, mode, { x: 1, y, z: 3 }, botName("GTx"));
  const yb = spawnBot(test, mode, { x: 1, y, z: 12 }, botName("GTy"));
  if (!(await waitGrounded(test, [x, yb]))) return;
  const rt = runtime();
  const xId = rt.adoptBot(x, x.name);
  const yId = rt.adoptBot(yb, yb.name);

  const t1 = absCell(test, { x: 14, y, z: 3 }); // A1's task -> first idle bot (registration order: x)
  const t2 = absCell(test, { x: 14, y, z: 12 }); // A2's task -> the other bot
  const t3 = absCell(test, { x: 8, y, z: 8 }); // B's position for !come
  // Different owners, so no per-player cooldown wait is needed. A1's task is the oldest, so !override
  // must take x and requeue A1's task at the front.
  const a1 = sender("A1", t1);
  const a2 = sender("A2", t2);
  const b = sender("B", t3);

  rt.submitText(a1, gotoText(t1));
  await test.idle(1); // distinct createdAt ticks -> deterministic "oldest"
  rt.submitText(a2, gotoText(t2));
  const a1Task = expectTask(test, xId, t1, a1.name, "A1's goto");
  if (!a1Task || !expectTask(test, yId, t2, a2.name, "A2's goto")) return;

  // Both busy with other players' tasks -> B's !come must create an offer and change nothing else.
  const offersBefore = rt.snapshot().pendingOffers;
  rt.submitText(b, "!come");
  const afterCome = rt.snapshot();
  if (afterCome.pendingOffers !== offersBefore + 1 || view(xId)?.task?.id !== a1Task) {
    return test.fail(`!come with all bots busy should only create an offer. ${snapStr()}`);
  }

  // !override (cooldown-exempt) takes x (oldest other-owner task) and requeues A1's task at the front.
  rt.submitText(b, "!override");
  if (!expectTask(test, xId, t3, b.name, "after !override")) return;
  if (!expectTask(test, yId, t2, a2.name, "untouched bot after !override")) return;
  const head = rt.snapshot().queued[0];
  if (head?.id !== a1Task) return test.fail(`A1's task ${a1Task} should head the queue. ${snapStr()}`);

  // Whichever bot frees first must pick A1's requeued task up (same task id) and finish it.
  const picked = await waitFor(test, () => [xId, yId].some((id) => view(id)?.task?.id === a1Task), 800);
  if (picked < 0) return test.fail(`A1's requeued task was never picked up. ${snapStr()}`);
  const pickerId = view(xId)?.task?.id === a1Task ? xId : yId;
  const picker = pickerId === xId ? x : yb;
  const done = await waitFor(test, () => isIdle(pickerId), 600);
  if (done < 0 || !near(picker, t1)) {
    return test.fail(`A1's requeued task didn't complete at ${fmt(t1)}. ${where(test, picker)}. ${snapStr()}`);
  }
  test.print(`override_flow(${mode}): ${x.name} reassigned to B; ${picker.name} picked up and finished A1's requeued task.`);
  test.succeed();
}

// ---------------------------------------------------------------- registration

type Body = (test: Test, mode: SpawnMode) => Promise<void>;

function reg(name: string, structure: string, maxTicks: number, body: Body): void {
  for (const mode of ["test", "toplevel"] as const) {
    const testName = mode === "test" ? name : `${name}_abs`;
    try {
      registerAsync(CLASS, testName, (test) => body(test, mode))
        .structureName(structure)
        .maxTicks(maxTicks)
        .setupTicks(5)
        .padding(4)
        .batch(`colony_${testName}`) // one test per batch: the runtime is a shared singleton
        .required(true)
        .tag(TAG);
    } catch (e) {
      // Never break script load because of test registration.
      void e;
    }
  }
}

reg("goto_flat", "colony:flat", 1200, gotoFlat);
reg("goto_unreachable", "colony:walled", 1600, gotoUnreachable);
reg("override_flow", "colony:flat", 2000, overrideFlow);
